### ISSUE TITLE
BUG? ValueError("Too Much Spent")

### ISSUE THREAD

**Issue by westurner** [JeremyRubin/tinycoin#3]
Is this correct? Why is it `>=`?

Maybe I've misunderstood?

```python
if not self.utxos[tx.parent].amount >= tx.amount_spent():
                raise ValueError("Too Much Spent")
```

https://github.com/JeremyRubin/tinycoin/blob/master/chain.py

**Comment by JeremyRubin** [comment]
Hey! Thanks for taking a look -- the tinycoin project is really just a toy for educational purposes, and has no sort of pretension around being correct.

In this case, I do believe it is correct.

What we're saying is as follows:

If the paren't amount is NOT greater than or equal to the amount spent, throw an error.

This is invertible to saying that the `tx.amount_spent()` should be less than the parent amount.


Thanks for taking a look!

**Comment by westurner** [comment]
Ah, I must've missed the `not` without parens and forgotten the precedence of operations.

```python
not 0 >= 0    # False
not (0 >= 0)  # False
(not 0) >= 0  # True
```

Is there any good reason to specify the expression with the extra boolean instead of just inverting the comparison?

AFAIU, the black code formatter doesn't attempt to simplify these but does do pep8ification.

**Comment by JeremyRubin** [comment]
I wrote it that way at the time because I thought it was more clear. If you want to do a PR here, with whatever cleanups happy to take them but this project is essentially archived :)

**Comment by westurner** [comment]
I'd hate to impose a particular style guide and add my name to the git blame for like every line here.

**Comment by JeremyRubin** [comment]
It's not an actively maintained project at all -- it's just an educational resource. If you care to make it better and more accessible, I'm happy to have your commits (I just won't have that much time to do thorough review)
